### ISSUE TITLE
Touch screen support

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/tw-sliders#5]

**Comment by luukdv** [comment]
Cycle2 has always felt heavy to me. Sometimes we need additional features like nesting or carousels in which case it's a good fit, but most of the time we only need one thing: sliding an element to another position. I like this one for example:

https://github.com/twbs/bootstrap/blob/master/js/carousel.js (7 kb non-minified)

In comparison: https://github.com/malsup/cycle2/blob/master/build/jquery.cycle2.js (49 kb non-minified)

I agree we should do a bit of research on this, since there are a lot of alternatives.

**Comment by haroldangenent** [comment]
Closing this issue, since this plugin is discontinued.
